
services:
  nginx:
    container_name: nginx
    image: nginx
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - frontend:/var/www/html:ro
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/conf/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf:ro

    networks:
      - transcendence
    depends_on:
      - frontend
      - backend
    ports:
      - "443:443"
    restart: on-failure

  backend:
    container_name: backend
    build:
      context: ./requirements/backend
    networks:
      - transcendence
    restart: unless-stopped
    expose:
      - "3000"

  frontend:
    container_name: frontend
    build:
      context: requirements/frontend
      dockerfile: Dockerfile
    networks:
      - transcendence
    volumes:
      - frontend:/app/dist
    depends_on:
      - backend
    restart: on-failure

volumes:
  frontend:
    driver: local

networks:
 transcendence:
  driver: bridge

