
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - transcendence
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file : .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./requirements/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - transcendence
    depends_on:
      - frontend
      - backend
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  backend:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
    restart: on-failure
  frontend:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      - backend
    ports:
      - "3000:80"   # Nginx ou serveur statique frontend
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/misaac-c/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/misaac-c/data/mariadb'

networks:
 transcendence:
  driver: bridge

